const nameList = () => [ 
//ランダムに生成された50人の名前
  "Jasmine Gonzalez",
  "Luke Ross",
  "Olivia Lee",
  "Ethan Nguyen",
  "Avery Rodriguez",
  "Abigail Murphy",
  "Nicholas Kim",
  "Samantha Johnson",
  "Mason Davis",
  "Lila Martin",
  "William Wilson",
  "Sophia Chen",
  "Michael Martinez",
  "Emma Taylor",
  "Daniel Brown",
  "Madison Jackson",
  "Alexander Lee",
  "Evelyn Nguyen",
  "David Rodriguez",
  "Emily Hernandez",
  "Gabriel Wilson",
  "Isabella Garcia",
  "John Kim",
  "Aria Miller",
  "Josephine Martinez",
  "Cameron Davis",
  "Madelyn Nguyen",
  "Anthony Jackson",
  "Victoria Perez",
  "Andrew Davis",
  "Hailey Lee",
  "Christopher Kim",
  "Makayla Thompson",
  "Benjamin Hernandez",
  "Chloe Martinez",
];

module.exports = nameList; 
